#!/bin/sh

echo "Setup Discord rich presence"
for i in {0..9}; do
    test -S $XDG_RUNTIME_DIR/discord-ipc-$i ||
    ln -sf {app/com.discordapp.Discord,$XDG_RUNTIME_DIR}/discord-ipc-$i;
done


# Launch Dolphin and point it to the user directory
project-plus-dolphin -u /var/data/project-plus-dolphin/user "$@"
